Repository Cockple/Cockple_FE, pull requests merged in 2025-08, with the labels that each got.

#94 [FEAT] 이전 기능들 수정보완
  src/components/alert/alertList.ts
  src/components/chat/ChatDetailTemplate.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/GroupChatDetailTemplate.tsx
  src/components/chat/ImagePreviewModal.tsx
  src/components/chat/groupDummy.ts
  src/components/chat/personalDummy.ts
  src/components/common/chat/BottomChatInput.tsx
  src/components/common/chat/ChattingComponent.tsx
  src/components/common/contentcard/alertTest/AlertTest1.tsx
  src/pages/alarm/AlertPage.tsx
  src/pages/chat/GroupChatDetailPage.tsx
Labels: bug

#103 [FEAT] 찜 경고 모달창
  src/components/like/CautionExerciseModal.tsx
  src/components/like/CautionGroupModal.tsx
Labels: enhancement

#116 [FEAT] 게스트 초대하기 api연동
  src/api/Exercise/InviteGuest.ts
  src/components/common/contentcard/Member.tsx
  src/pages/group/InviteGuest.tsx
  src/pages/onboarding/OnboardingConfirmPage.tsx
  src/types/guest.ts
  src/utils/levelValueExchange.ts
  src/utils/onboardingAPIMap.ts
Labels: enhancement

#117 [Feat] 찜 api 연동 완성/ 알림 api 연동 진행 중/ 채팅 api 연동 진행중
  src/App.tsx
  src/api/bookmark/bookmark.ts
  src/api/chat/chatList.ts
  src/api/chat/chattingMessage.ts
  src/components/alert/alertList.ts
  src/components/chat/ChatDetailTemplate.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/GroupChatDetailTemplate.tsx
  src/components/common/contentcard/ContentCardL.tsx
  src/components/common/contentcard/Group_M.tsx
  src/components/common/contentcard/Member.tsx
  src/components/like/LikedList.tsx
  src/components/like/groupDummy.ts
  src/hooks/useLikedItems.ts
  src/pages/alarm/AlertPage.tsx
  src/pages/chat/ChatPage.tsx
  src/pages/chat/GroupChatDetailPage.tsx
  src/pages/chat/PersonalChatDetailPage.tsx
  src/pages/group/GroupChatPage.tsx
  src/pages/group/MemberRequest.tsx
  src/pages/like/LikedPage.tsx
  src/types/alert.ts
  src/types/chat.ts
  src/types/common.ts
  src/types/liked.ts
  src/types/memberJoinRequest.ts
Labels: enhancement, high, feature

#126 [BUG] 빨간 줄 수정!!
  src/api/chat/chattingMessage.ts
  src/api/chat/readSender.ts
  src/components/alert/alertList.ts
  src/components/chat/GroupChatDetailTemplate.tsx
  src/components/chat/groupChatMessageDummy.ts
  src/components/chat/groupDummy.ts
  src/components/chat/personalChatMessageDummy.ts
  src/components/chat/personalDummy.ts
  src/components/common/chat/ChattingComponent.tsx
  src/hooks/useChatInfinite.ts
  src/hooks/useChatRead.ts
  src/hooks/useMockChatInfinite.ts
  src/pages/group/GroupChatPage.tsx
  src/pages/group/MemberRequest.tsx
Labels: bug

#181 [FEAT] 모임-> 채팅 오류 해결
  src/api/chat/chatList.ts
  src/api/chat/getRoomIdByPartyId.ts
  src/components/chat/GroupChatDetailTemplate.tsx
  src/pages/alarm/AlertPage.tsx
  src/pages/group/GroupChatPage.tsx
Labels: bug, enhancement
