Repository Cockple/Cockple_FE, pull requests merged in 2025-07, with the labels that each got.

#7 [FEAT]DynamicBtn 컴포넌트
  src/assets/icons/arrow_downG.svg
  src/assets/icons/arrow_rightG.svg
  src/assets/icons/arrow_right_fill.svg
  src/assets/icons/check_circledG.svg
  src/assets/icons/dismiss_fill.svg
  src/assets/icons/filterG.svg
  src/assets/icons/filter_fill.svg
  src/assets/images/image.png
  src/components/common/DynamicBtn/ChatBtn.tsx
  src/components/common/DynamicBtn/CheckBoxBtn.tsx
  src/components/common/DynamicBtn/DropDownBtn.tsx
  src/components/common/DynamicBtn/DynamicBtn.tsx
  src/components/common/DynamicBtn/FilterBtn.tsx
  src/components/common/DynamicBtn/TabBtn.tsx
  src/components/common/DynamicBtn/TagBtn.tsx
  src/components/common/DynamicBtn/TextIconBtnM.tsx
  src/components/common/DynamicBtn/TextIconBtnS.tsx
  src/hooks/useDynamicStatus.ts
  src/types/DynamicBtn.ts
Labels: enhancement

#10 [FEAT] 라우팅 설정
  src/App.tsx
  src/components/common/system/header/PageHeader.tsx
  src/components/common/system/navbar/Navbar.tsx
  src/index.css
  src/layout/NavbarLayout.tsx
  src/layout/PrivateRoute.tsx
  src/pages/alarm/AlarmPage.tsx
  src/pages/chat/ChatDetailPage.tsx
  src/pages/chat/ChatPage.tsx
  src/pages/group/GroupPage.tsx
  src/pages/group/index.ts
  src/pages/home/ExerciseMapPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/home/Recommendpage.tsx
  src/pages/like/LikedPage.tsx
  src/pages/login/LoginPage.tsx
  src/pages/login/SplashPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyPageEditLocationPage.tsx
  src/pages/mypage/MyPageEditPage.tsx
  src/pages/mypage/MyPageExerciseDetailPage.tsx
  src/pages/mypage/MyPageMedalAddpage.tsx
  src/pages/mypage/MyPageMedalDetailPage.tsx
  src/pages/mypage/MyPageMyExercisePage.tsx
  src/pages/mypage/MyPageMyGroupPage.tsx
  src/pages/mypage/MyPageMyMedalPage.tsx
  src/pages/mypage/index.ts
  src/pages/onboarding/OnboardingAddressPage.tsx
  src/pages/onboarding/OnboardingConfirmPage.tsx
  src/pages/onboarding/OnboardingInfoPage.tsx
  src/pages/onboarding/OnboardingLevelPage.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/OnboardingProfilePage.tsx
  src/pages/onboarding/index.ts
Labels: enhancement

#12 [FEAT] Btn_Static 리팩토링
  package-lock.json
  package.json
  src/assets/icons/arrow_left-gy-400.svg
  src/assets/icons/arrow_left_white.svg
  src/assets/icons/arrow_right_gy_400.svg
  src/assets/icons/camera_gy_400.svg
  src/assets/icons/delete-gy-400.svg
  src/assets/icons/delete-rd-500.svg
  src/assets/icons/delete-white.svg
  src/assets/icons/heart_GY300.svg
  src/assets/icons/heart_GY400.svg
  src/assets/icons/heart_filled_GY300.svg
  src/assets/icons/heart_filled_systemError.svg
  src/assets/icons/pen-gr-600.svg
  src/assets/icons/pen-gy-400.svg
  src/assets/icons/pen-rd-500.svg
  src/assets/icons/refresh-gy-400.svg
  src/assets/icons/refresh-white.svg
  src/components/common/Btn_Static/Btn_Static.tsx
  src/components/common/Btn_Static/Icon_Btn/Add_Photo_M.tsx
  src/components/common/Btn_Static/Icon_Btn/Clear_M.tsx
  src/components/common/Btn_Static/Icon_Btn/Clear_XS.tsx
  src/components/common/Btn_Static/Icon_Btn/GY800_M.tsx
  src/components/common/Btn_Static/Icon_Btn/RD500_S.tsx
  src/components/common/Btn_Static/Icon_Btn/White_M_Round.tsx
  src/components/common/Btn_Static/Text/Grad_GR400_L.tsx
  src/components/common/Btn_Static/Text/Grad_Mix_L.tsx
  src/components/common/Btn_Static/Text/White_L_Test.tsx
  src/components/common/Btn_Static/presets.ts
  src/components/common/Btn_Static/types.ts
Labels: enhancement

#6 Feat/#2 ContentCard
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  eslint.config.js
  package-lock.json
  package.json
  src/assets/icons/Heart.svg
  src/assets/icons/Num_Noti.svg
  src/assets/icons/Num_Noti_99.svg
  src/assets/icons/ProfileImage.svg
  src/assets/icons/RightAngle.svg
  src/assets/icons/Vector.svg
  src/assets/icons/arrow_right_GY.svg
  src/assets/icons/calendar.svg
  src/assets/icons/clock.svg
  src/assets/icons/female.svg
  src/assets/icons/heart_GY.svg
  src/assets/icons/male.svg
  src/assets/icons/message.svg
  src/assets/icons/people.svg
  src/assets/icons/prohibition.svg
  src/assets/icons/star.svg
  src/assets/images/Profile_Image.png
  src/assets/images/kitty.png
  src/components/common/contentcard/ContentCardL.tsx
  src/components/common/contentcard/DailyExercise_S.tsx
  src/components/common/contentcard/Exercise_M.tsx
  src/components/common/contentcard/Exercise_S.tsx
  src/components/common/contentcard/GroupChat.tsx
  src/components/common/contentcard/Group_M.tsx
  src/components/common/contentcard/Group_S.tsx
  src/components/common/contentcard/Location.tsx
  src/components/common/contentcard/LocationList.tsx
  src/components/common/contentcard/Member.tsx
  src/components/common/contentcard/MyMedal.tsx
  src/components/common/contentcard/MyPage.tsx
  src/components/common/contentcard/PersonalChat.tsx
  src/components/common/contentcard/stories/ContentCardL.stories.tsx
  src/components/common/contentcard/stories/DailyExercise_S.stories.tsx
  src/components/common/contentcard/stories/Exercise_M.stories.tsx
  src/components/common/contentcard/stories/Exercise_S.stories.tsx
  src/components/common/contentcard/stories/GroupChat.stories.tsx
  src/components/common/contentcard/stories/Group_M.stories.tsx
  src/components/common/contentcard/stories/Group_S.stories.tsx
  src/components/common/contentcard/stories/Location.stories.tsx
  src/components/common/contentcard/stories/LocationList.stories.tsx
  src/components/common/contentcard/stories/Member.stories.tsx
  src/components/common/contentcard/stories/MyMedal.stories.tsx
  src/components/common/contentcard/stories/MyPage.stories.tsx
  src/components/common/contentcard/stories/PersonalChat.stories.tsx
  vite.config.ts
  vitest.shims.d.ts
Labels: enhancement, feature

#21 [FIX] 최대 레이아웃 크기 설정 & navbar 아이콘 크기 수정
  src/App.tsx
  src/assets/icons/heart_black.svg
  src/components/common/system/navbar/NavItem.tsx
  src/components/common/system/navbar/Navbar.tsx
  vite.config.ts
Labels: bug

#19 [FIX] Tab 오류 수정
  package-lock.json
  src/components/common/DynamicBtn/TabBtn.tsx
Labels: bug

#26 [FEAT] MyPage 공용 컴포넌트 수정 및 UI제작(미완성: /Profile,/MyPage/MyMedal, 기능X) #17
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/Vector_red.svg
  src/assets/icons/map_marker.svg
  src/components/MyPage/Modal_Caution.tsx
  src/components/MyPage/MyExerciseSort.tsx
  src/components/MyPage/MyGroupNone.tsx
  src/components/MyPage/Profile.tsx
  src/components/MyPage/Select.tsx
  src/components/MyPage/Sort.tsx
  src/components/common/contentcard/ContentCardL.tsx
  src/components/common/contentcard/GroupChat.tsx
  src/components/common/contentcard/Member.tsx
  src/components/common/contentcard/MyPage.tsx
  src/components/common/contentcard/MyPage_Medal.tsx
  src/components/common/contentcard/MyPage_Text.tsx
  src/components/common/contentcard/Num_Noti.tsx
  src/components/common/contentcard/PersonalChat.tsx
  src/components/common/contentcard/stories/ContentCardL.stories.tsx
  src/components/common/contentcard/stories/GroupChat.stories.tsx
  src/components/common/contentcard/stories/MyPage.stories.tsx
  src/components/common/contentcard/stories/MyPageExercisePAge.stories.tsx
  src/components/common/contentcard/stories/MyPageMyGroupPage.stories.tsx
  src/components/common/contentcard/stories/MyPage_Medal.stories.tsx
  src/components/common/contentcard/stories/MyPage_Text.stories copy.tsx
  src/components/common/contentcard/stories/PersonalChat.stories.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyPageAddressSearchPage.tsx
  src/pages/mypage/MyPageEditLocationPage.tsx
  src/pages/mypage/MyPageEditPage.tsx
  src/pages/mypage/MyPageExerciseDetailPage.tsx
  src/pages/mypage/MyPageMyExercisePage.tsx
  src/pages/mypage/MyPageMyGroupPage.tsx
  src/pages/mypage/index.ts
  vite.config.ts
Labels: enhancement

#28 [FEAT]RD500_S_Icon(하트 아이콘) 수정 및 Sort.tsx(공통 컴포넌트) 생성
  src/App.tsx
  src/components/chat/ChatDetailTemplate.tsx
  src/components/chat/ChatList.tsx
  src/components/chat/ChattingComponent.tsx
  src/components/chat/FileSendModal.tsx
  src/components/chat/ImagePreviewModal.tsx
  src/components/chat/SearchInput.tsx
  src/components/common/Btn_Static/Icon_Btn/RD500_S_Icon.tsx
  src/components/common/Sort.tsx
  src/components/common/TabSelector.tsx
  src/pages/chat/ChatDetailPage.tsx
  src/pages/chat/ChatPage.tsx
  src/pages/chat/ChattingComponent.tsx
  src/pages/chat/GroupChatDetailPage.tsx
  src/pages/chat/PersonalChatDetailPage.tsx
  src/types/chat.ts
  src/utils/disassembleHangul.ts
Labels: enhancement, feature

#31 [FEAT] 온보딩 UI제작
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/cicle_s_red.svg
  src/assets/icons/img_Edit.svg
  src/assets/icons/mylocation_g.svg
  src/assets/images/base_profile_img.png
  src/assets/images/profile_Image.png
  src/components/common/Date_Time/DateAndPicker.tsx
  src/components/common/Date_Time/Picker.tsx
  src/components/common/DynamicBtn/TagBtn.tsx
  src/components/common/Etc/ProfileImg.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/Search_Filed/SearchField.tsx
  src/components/common/Search_Filed/SearchFieldBtn.tsx
  src/components/common/Text_Box/TextBox.tsx
  src/components/common/system/header/PageHeader.tsx
  src/index.css
  src/pages/login/LoginPage.tsx
  src/pages/login/LoginSwiping.tsx
  src/pages/onboarding/OnBoardingConfirmStartPage.tsx
  src/pages/onboarding/OnboardingAddressPage.tsx
  src/pages/onboarding/OnboardingAddressSearchPage.tsx
  src/pages/onboarding/OnboardingConfirmPage.tsx
  src/pages/onboarding/OnboardingInfoPage.tsx
  src/pages/onboarding/OnboardingLevelPage.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/OnboardingProfilePage.tsx
  src/pages/onboarding/onBoardingLayout.tsx
  src/types/DynamicBtn.ts
Labels: enhancement, high

#32 [FEAT] disabled->default 같은 상태 변경 가능하도록 리팩토링
  src/components/common/Btn_Static/Btn_Static.tsx
  src/components/common/Btn_Static/Text/Grad_GR400_L.tsx
  src/components/common/Btn_Static/Text/Grad_Mix_L.tsx
Labels: enhancement

#33 [FEAT] ChatList(채팅 컴포넌트), TabSelector(TabBtn 이용한 컴포넌트) 수정
  src/components/chat/ChatList.tsx
  src/components/common/TabSelector.tsx
Labels: feature

#36 [FEAT] Like 페이지 완료
  src/components/like/LikedList.tsx
  src/components/like/exerciseDummy.ts
  src/components/like/groupDummy.ts
  src/pages/like/LikedPage.tsx
Labels: feature

#42 [FEAT] 달력컴포넌트와 스플래쉬 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/cicle_s_fill.svg
  src/assets/images/Logo_Typo.png
  src/components/common/Date_Time/DateAndPicker.tsx
  src/components/common/Date_Time/DayNum.tsx
  src/components/common/Date_Time/MonthCalendar.tsx
  src/components/common/Date_Time/MonthNum.tsx
  src/components/common/Date_Time/Picker.tsx
  src/components/common/Date_Time/RenderPickerGroup.tsx
  src/components/common/Date_Time/WeeklyCalendar.tsx
  src/components/common/Date_Time/utils/generateMonthDates.ts
  src/components/common/system/SplashScreen.tsx
  src/index.css
  src/pages/onboarding/OnboardingAddressSearchPage.tsx
  src/pages/onboarding/OnboardingInfoPage.tsx
  src/zustand/useSplashStore.ts
Labels: enhancement

#49 [Feat] 공용 컴포넌트 생성, 적용 및 수정
  src/components/chat/ChatDetailTemplate.tsx
  src/components/common/DynamicBtn/ChatBtn.tsx
  src/components/common/DynamicBtn/TabBtn.tsx
  src/components/common/TabSelector.tsx
  src/components/common/chat/BottomChatInput.tsx
  src/components/common/chat/ChattingComponent.tsx
  src/pages/chat/ChatPage.tsx
  src/pages/like/LikedPage.tsx
  src/types/chat.ts
Labels: enhancement

#62 [FEAT] 채팅창 이미지 모달창 수정 및 채팅창 날짜 표시
  src/components/alert/NoAlertMessage.tsx
  src/components/chat/ChatDataSeperator.tsx
  src/components/chat/ChatDetailTemplate.tsx
  src/components/chat/ImagePreviewModal.tsx
  src/components/common/Btn_Static/Icon_Btn/Clear_M.tsx
  src/components/like/exerciseDummy.ts
  src/components/like/groupDummy.ts
  src/hooks/useIsStandalone.ts
  src/pages/alarm/AlertPage.tsx
  src/pages/chat/ChatPage.tsx
  src/pages/chat/PersonalChatDetailPage.tsx
  src/pages/like/LikedPage.tsx
  src/types/chat.ts
  src/utils/getLocalDateString.ts
Labels: feature

#82 [FEAT] 모임 게스트 페이지, 모임 만들기 페이지 제작
  package-lock.json
  package.json
  src/App.tsx
  src/components/MyPage/Modal_Caution.tsx
  src/components/chat/SearchInput.tsx
  src/components/common/Drop_Box/DropCheckBox.tsx
  src/components/common/Search_Filed/InputField.tsx
  src/components/common/Search_Filed/InputSlider.tsx
  src/components/group/groupMaking/CheckBoxInputField.tsx
  src/components/group/groupMaking/GroupFilter.tsx
  src/components/group/groupMaking/GroupMember.tsx
  src/components/group/groupMaking/InviteModal.tsx
  src/components/group/groupMaking/MemberCard.tsx
  src/components/group/groupMaking/MemberInfo.tsx
  src/components/group/groupMaking/SingleImgUploadBtn.tsx
  src/components/login/LoginSwiping.tsx
  src/components/login/SplashScreen.tsx
  src/components/onboarding/IntroText.tsx
  src/pages/group/InviteGuest.tsx
  src/pages/group/groupMaking/GroupActivity.tsx
  src/pages/group/groupMaking/GroupBasicInfo.tsx
  src/pages/group/groupMaking/GroupFilter.tsx
  src/pages/group/groupMaking/GroupMember.tsx
  src/pages/group/groupMaking/GroupSelect.tsx
  src/pages/login/LoginPage.tsx
  src/pages/onboarding/OnBoardingConfirmStartPage.tsx
  src/pages/onboarding/OnboardingAddressPage.tsx
  src/pages/onboarding/OnboardingConfirmPage.tsx
  src/pages/onboarding/OnboardingLevelPage.tsx
  src/pages/onboarding/OnboardingPage.tsx
  src/pages/onboarding/OnboardingProfilePage.tsx
  src/pages/onboarding/index.ts
  src/zustand/useGroupMakingFilter.ts
Labels: enhancement, high
